node {
	stage ('SCM checkout'){
		git "https://github.com/KiranKumar514/MYB.git"
		}
	stage ('Run tests'){
	    withMaven(maven: 'Maven 3'){
    	dir("MBTEST") {
	   sh 'mvn clean install'
       }
       	dir("MBTEST/target") {
	   sh "java -jar com.test-1.0-SNAPSHOT.jar"
       }
    }
  }
}